  title: "[Bug] "
  labels: []
  body:
    - type: markdown
      attributes:
        value: |
          Thanks for reporting a bug! Please fill out the details below.

    - type: input
      id: browser
      attributes:
        label: Browser & Version
        placeholder: e.g., Chrome 120
      validations:
        required: true

    - type: input
      id: os
      attributes:
        label: Operating System
        placeholder: e.g., macOS Sonoma
      validations:
        required: true

    - type: textarea
      id: steps
      attributes:
        label: Steps to Reproduce
        placeholder: |
          1. Open a project
          2. Click on...
          3. See error
      validations:
        required: true

    - type: textarea
      id: expected
      attributes:
        label: Expected Behavior
      validations:
        required: true

    - type: textarea
      id: actual
      attributes:
        label: Actual Behavior
      validations:
        required: true

    - type: textarea
      id: screenshots
      attributes:
        label: Screenshots
        description: Drag and drop images here if applicable.
      validations:
        required: false
